# Generated by Django 3.2.18 on 2023-05-18 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_regex', message='При вводе имен/фамилий/названий рецептов допустимы только буквы кириллицы и латиницы. Проверьте введенные данные', regex='/^([а-яё]+|[a-z]+)$/i')], verbose_name='Название рецепта'),
        ),
    ]
