# Generated by Django 3.2.18 on 2023-05-18 17:50

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=200, validators=[users.validators.NamesValidator()], verbose_name='Название рецепта'),
        ),
    ]
