# Generated by Django 3.2.18 on 2023-05-03 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230503_0755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingredients',
            new_name='ingredient',
        ),
    ]
