# Generated by Django 3.2.18 on 2023-05-03 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_rename_ingredients_ingredientamount_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ingredientamount',
            old_name='ingredient',
            new_name='ingredients',
        ),
    ]
