# Generated by Django 3.2.18 on 2023-05-11 15:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230511_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('[A-zА-яЁё]', 'Имя: допустимы только буквы кириллицы и латиницы')], verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator('[A-zА-яЁё]', 'Фамилия: допустимы только буквы кириллицы и латиницы')], verbose_name='Фамилия'),
        ),
    ]
